[2022-02-24 03:29:35,286] {processor.py:163} INFO - Started process (PID=124) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:29:35,303] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:29:35,308] {logging_mixin.py:109} INFO - [2022-02-24 03:29:35,308] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:29:35,513] {logging_mixin.py:109} INFO - [2022-02-24 03:29:35,488] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:29:35,573] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:29:35,636] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.362 seconds
[2022-02-24 03:30:06,179] {processor.py:163} INFO - Started process (PID=226) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:30:06,204] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:30:06,208] {logging_mixin.py:109} INFO - [2022-02-24 03:30:06,207] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:30:06,276] {logging_mixin.py:109} INFO - [2022-02-24 03:30:06,268] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:30:06,316] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:30:06,345] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.172 seconds
[2022-02-24 03:30:36,582] {processor.py:163} INFO - Started process (PID=324) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:30:36,590] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:30:36,595] {logging_mixin.py:109} INFO - [2022-02-24 03:30:36,594] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:30:36,684] {logging_mixin.py:109} INFO - [2022-02-24 03:30:36,674] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:30:36,719] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:30:36,767] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.203 seconds
[2022-02-24 03:31:07,588] {processor.py:163} INFO - Started process (PID=416) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:31:07,594] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:31:07,597] {logging_mixin.py:109} INFO - [2022-02-24 03:31:07,597] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:31:07,669] {logging_mixin.py:109} INFO - [2022-02-24 03:31:07,658] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:31:07,707] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:31:07,739] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.159 seconds
[2022-02-24 03:31:38,291] {processor.py:163} INFO - Started process (PID=522) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:31:38,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:31:38,300] {logging_mixin.py:109} INFO - [2022-02-24 03:31:38,299] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:31:38,372] {logging_mixin.py:109} INFO - [2022-02-24 03:31:38,354] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:31:38,409] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:31:38,436] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.153 seconds
[2022-02-24 03:32:09,058] {processor.py:163} INFO - Started process (PID=610) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:32:09,063] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:32:09,066] {logging_mixin.py:109} INFO - [2022-02-24 03:32:09,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:32:09,145] {logging_mixin.py:109} INFO - [2022-02-24 03:32:09,127] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:32:09,178] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:32:09,205] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.156 seconds
[2022-02-24 03:32:39,333] {processor.py:163} INFO - Started process (PID=712) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:32:39,339] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:32:39,342] {logging_mixin.py:109} INFO - [2022-02-24 03:32:39,341] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:32:39,394] {logging_mixin.py:109} INFO - [2022-02-24 03:32:39,385] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:32:39,426] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:32:39,456] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.130 seconds
[2022-02-24 03:33:09,802] {processor.py:163} INFO - Started process (PID=803) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:33:09,809] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:33:09,812] {logging_mixin.py:109} INFO - [2022-02-24 03:33:09,812] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:33:09,868] {logging_mixin.py:109} INFO - [2022-02-24 03:33:09,859] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:33:09,902] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:33:09,929] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.135 seconds
[2022-02-24 03:33:40,385] {processor.py:163} INFO - Started process (PID=910) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:33:40,391] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:33:40,403] {logging_mixin.py:109} INFO - [2022-02-24 03:33:40,403] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:33:40,511] {logging_mixin.py:109} INFO - [2022-02-24 03:33:40,499] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:33:40,559] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:33:40,593] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.222 seconds
[2022-02-24 03:34:10,922] {processor.py:163} INFO - Started process (PID=998) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:34:10,929] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:34:10,932] {logging_mixin.py:109} INFO - [2022-02-24 03:34:10,932] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:34:10,987] {logging_mixin.py:109} INFO - [2022-02-24 03:34:10,977] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:34:11,023] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:34:11,051] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.138 seconds
[2022-02-24 03:34:41,746] {processor.py:163} INFO - Started process (PID=1109) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:34:41,749] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:34:41,753] {logging_mixin.py:109} INFO - [2022-02-24 03:34:41,752] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:34:41,802] {logging_mixin.py:109} INFO - [2022-02-24 03:34:41,793] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:34:41,835] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:34:41,860] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.121 seconds
[2022-02-24 03:35:12,825] {processor.py:163} INFO - Started process (PID=1198) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:35:12,830] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:35:12,833] {logging_mixin.py:109} INFO - [2022-02-24 03:35:12,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:35:12,885] {logging_mixin.py:109} INFO - [2022-02-24 03:35:12,875] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
  File "/opt/airflow/dags/reddit_posts.py", line 2, in <module>
    import train_data as train  # import train_data.py
  File "/opt/airflow/dags/train_data.py", line 4, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
[2022-02-24 03:35:12,918] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:35:12,944] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.127 seconds
[2022-02-24 03:35:43,109] {processor.py:163} INFO - Started process (PID=1303) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:35:43,114] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:35:43,118] {logging_mixin.py:109} INFO - [2022-02-24 03:35:43,117] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:35:43,168] {logging_mixin.py:109} INFO - [2022-02-24 03:35:43,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
ModuleNotFoundError: No module named 'reddit_posts'
[2022-02-24 03:35:43,203] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:35:43,232] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.131 seconds
[2022-02-24 03:36:13,848] {processor.py:163} INFO - Started process (PID=1391) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:36:13,852] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:36:13,856] {logging_mixin.py:109} INFO - [2022-02-24 03:36:13,855] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:36:13,891] {logging_mixin.py:109} INFO - [2022-02-24 03:36:13,886] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
ModuleNotFoundError: No module named 'reddit_posts'
[2022-02-24 03:36:13,922] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:36:13,945] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.104 seconds
[2022-02-24 03:36:44,442] {processor.py:163} INFO - Started process (PID=1495) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:36:44,447] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:36:44,451] {logging_mixin.py:109} INFO - [2022-02-24 03:36:44,450] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:36:44,496] {logging_mixin.py:109} INFO - [2022-02-24 03:36:44,490] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
ModuleNotFoundError: No module named 'reddit_posts'
[2022-02-24 03:36:44,531] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:36:44,556] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.120 seconds
[2022-02-24 03:37:14,954] {processor.py:163} INFO - Started process (PID=1582) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:37:14,958] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:37:14,960] {logging_mixin.py:109} INFO - [2022-02-24 03:37:14,960] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:37:14,999] {logging_mixin.py:109} INFO - [2022-02-24 03:37:14,995] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
ModuleNotFoundError: No module named 'reddit_posts'
[2022-02-24 03:37:15,029] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:37:15,048] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.100 seconds
[2022-02-24 03:37:45,417] {processor.py:163} INFO - Started process (PID=1692) to work on /opt/airflow/dags/mydag.py
[2022-02-24 03:37:45,422] {processor.py:642} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2022-02-24 03:37:45,425] {logging_mixin.py:109} INFO - [2022-02-24 03:37:45,425] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2022-02-24 03:37:45,465] {logging_mixin.py:109} INFO - [2022-02-24 03:37:45,461] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9, in <module>
    import reddit_posts as reddit
ModuleNotFoundError: No module named 'reddit_posts'
[2022-02-24 03:37:45,496] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2022-02-24 03:37:45,522] {processor.py:171} INFO - Processing /opt/airflow/dags/mydag.py took 0.112 seconds
