[2022-02-24 20:01:04,483] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T09:00:00+00:00 [queued]>
[2022-02-24 20:01:04,855] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T09:00:00+00:00 [queued]>
[2022-02-24 20:01:04,866] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:04,871] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:01:04,886] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:01:05,346] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_reddit_data> on 2022-02-24 09:00:00+00:00
[2022-02-24 20:01:05,369] {standard_task_runner.py:52} INFO - Started process 624 to run task
[2022-02-24 20:01:05,407] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'get_reddit_data', 'scheduled__2022-02-24T09:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmprqm6tymf', '--error-file', '/tmp/tmpy_xckml5']
[2022-02-24 20:01:05,423] {standard_task_runner.py:77} INFO - Job 43: Subtask get_reddit_data
[2022-02-24 20:01:06,486] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T09:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 20:01:07,700] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=get_reddit_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T09:00:00+00:00
[2022-02-24 20:23:45,897] {logging_mixin.py:109} INFO - Negative
[2022-02-24 20:47:34,359] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2022-02-24 20:47:36,721] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 624. PIDs of all processes in the group: [624]
[2022-02-24 20:47:36,928] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 624
[2022-02-24 20:47:37,212] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-24 20:47:42,572] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 9, in <module>
    import s3 as s3boto
  File "/opt/airflow/dags/s3.py", line 25, in <module>
    region_name='us-east-1'
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 102, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 341, in resource
    service_name, 'resources-1', api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 375, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 284, in list_available_services
    type_name)
  File "/usr/local/lib/python3.7/posixpath.py", line 87, in join
    if b.startswith(sep):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:47:44,953] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=get_reddit_data, execution_date=20220224T090000, start_date=20220224T200104, end_date=20220224T204744
[2022-02-24 20:47:49,544] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task get_reddit_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 9, in <module>
    import s3 as s3boto
  File "/opt/airflow/dags/s3.py", line 25, in <module>
    region_name='us-east-1'
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 102, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 341, in resource
    service_name, 'resources-1', api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 375, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 284, in list_available_services
    type_name)
  File "/usr/local/lib/python3.7/posixpath.py", line 87, in join
    if b.startswith(sep):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:48:02,395] {process_utils.py:70} INFO - Process psutil.Process(pid=624, status='terminated', exitcode=1, started='20:01:04') (624) terminated with exit code 1
