[2022-02-24 18:29:36,747] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.reddit_posts scheduled__2022-02-23T00:00:00+00:00 [queued]>
[2022-02-24 18:29:36,918] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.reddit_posts scheduled__2022-02-23T00:00:00+00:00 [queued]>
[2022-02-24 18:29:36,924] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 18:29:36,930] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 18:29:36,940] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 18:29:37,059] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): reddit_posts> on 2022-02-23 00:00:00+00:00
[2022-02-24 18:29:37,079] {standard_task_runner.py:52} INFO - Started process 999 to run task
[2022-02-24 18:29:37,116] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'reddit_posts', 'scheduled__2022-02-23T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpjlbyf4s8', '--error-file', '/tmp/tmpk2j7_4ma']
[2022-02-24 18:29:37,122] {standard_task_runner.py:77} INFO - Job 30: Subtask reddit_posts
[2022-02-24 18:29:37,431] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.reddit_posts scheduled__2022-02-23T00:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 18:29:37,755] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=reddit_posts
AIRFLOW_CTX_EXECUTION_DATE=2022-02-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-23T00:00:00+00:00
[2022-02-24 18:29:37,766] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-24 18:29:37,777] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/***/dags/reddit_posts.py']
[2022-02-24 18:29:37,840] {subprocess.py:85} INFO - Output:
[2022-02-24 18:29:39,249] {subprocess.py:89} INFO - /usr/local/bin/python3: can't open file '/home/***/dags/reddit_posts.py': [Errno 2] No such file or directory
[2022-02-24 18:29:39,270] {subprocess.py:93} INFO - Command exited with return code 2
[2022-02-24 18:29:39,326] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-02-24 18:29:39,378] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=reddit_posts, execution_date=20220223T000000, start_date=20220224T182936, end_date=20220224T182939
[2022-02-24 18:29:39,453] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task reddit_posts
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-02-24 18:29:39,486] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-24 18:29:39,610] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
