[2022-02-24 20:00:54,658] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T05:00:00+00:00 [queued]>
[2022-02-24 20:00:54,977] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T05:00:00+00:00 [queued]>
[2022-02-24 20:00:54,999] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:00:55,005] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:00:55,011] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:00:55,181] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_reddit_data> on 2022-02-24 05:00:00+00:00
[2022-02-24 20:00:55,195] {standard_task_runner.py:52} INFO - Started process 600 to run task
[2022-02-24 20:00:55,227] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'get_reddit_data', 'scheduled__2022-02-24T05:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp1g4mmwre', '--error-file', '/tmp/tmpyrtwdokr']
[2022-02-24 20:00:55,234] {standard_task_runner.py:77} INFO - Job 39: Subtask get_reddit_data
[2022-02-24 20:00:55,841] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T05:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 20:00:56,352] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=get_reddit_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T05:00:00+00:00
[2022-02-24 20:23:21,140] {logging_mixin.py:109} INFO - Negative
[2022-02-24 20:47:33,280] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2022-02-24 20:47:36,277] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 600. PIDs of all processes in the group: [600]
[2022-02-24 20:47:36,668] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 600
[2022-02-24 20:47:36,928] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-24 20:47:42,776] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 200, in <module>
    reddit = Reddit()
  File "/opt/airflow/dags/reddit_data.py", line 51, in __init__
    if self.df['target'][i] == 0:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3418, in __getitem__
    def __getitem__(self, key):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:47:45,271] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=get_reddit_data, execution_date=20220224T050000, start_date=20220224T200054, end_date=20220224T204745
[2022-02-24 20:47:48,053] {standard_task_runner.py:92} ERROR - Failed to execute job 39 for task get_reddit_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 200, in <module>
    reddit = Reddit()
  File "/opt/airflow/dags/reddit_data.py", line 51, in __init__
    if self.df['target'][i] == 0:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3418, in __getitem__
    def __getitem__(self, key):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:48:00,163] {process_utils.py:70} INFO - Process psutil.Process(pid=600, status='terminated', exitcode=1, started='20:00:54') (600) terminated with exit code 1
